// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBtn: typeof import('./src/components/base/BaseBtn.vue')['default']
    BaseDivider: typeof import('./src/components/base/BaseDivider.vue')['default']
    BaseTable: typeof import('./src/components/base/base-table/BaseTable.vue')['default']
    BaseTableHead: typeof import('./src/components/base/base-table/BaseTableHead.vue')['default']
    BaseTableMenuButton: typeof import('./src/components/base/base-table/BaseTableMenuButton.vue')['default']
    BaseTableMenus: typeof import('./src/components/base/base-table/BaseTableMenus.vue')['default']
    BaseTableNoData: typeof import('./src/components/base/base-table/BaseTableNoData.vue')['default']
    BaseTableToolbar: typeof import('./src/components/base/base-table/BaseTableToolbar.vue')['default']
    BaseTableView: typeof import('./src/components/base/base-table/BaseTableView.vue')['default']
    DAppBar: typeof import('./src/components/layout-default/app-bar/DAppBar.vue')['default']
    DAppBarLogo: typeof import('./src/components/layout-default/app-bar/DAppBarLogo.vue')['default']
    DAppView: typeof import('./src/components/layout-default/app-view/DAppView.vue')['default']
    DLoginBtn: typeof import('./src/components/layout-default/app-bar/DLoginBtn.vue')['default']
    DPlaygroundBtn: typeof import('./src/components/layout-default/app-bar/DPlaygroundBtn.vue')['default']
    DTestRouteButton: typeof import('./src/components/layout-default/app-bar/DTestRouteButton.vue')['default']
    FourLanding: typeof import('./src/components/404/FourLanding.vue')['default']
    GradientTitle: typeof import('./src/components/base/GradientTitle.vue')['default']
    HomeLanding: typeof import('./src/components/home/HomeLanding.vue')['default']
    HomeSubtitle: typeof import('./src/components/home/HomeSubtitle.vue')['default']
    LoginButtonEmail: typeof import('./src/components/login/LoginButtonEmail.vue')['default']
    LoginButtons: typeof import('./src/components/login/LoginButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAppBar: typeof import('./src/components/layout-secure/app-bar/SAppBar.vue')['default']
    SAppBarLogo: typeof import('./src/components/layout-secure/app-bar/SAppBarLogo.vue')['default']
    SAppView: typeof import('./src/components/layout-secure/app-view/SAppView.vue')['default']
    SDrawer: typeof import('./src/components/layout-secure/app-drawer/SDrawer.vue')['default']
    SkriptagTitle: typeof import('./src/components/base/SkriptagTitle.vue')['default']
    SLoginBtn: typeof import('./src/components/layout-secure/app-bar/SLoginBtn.vue')['default']
    SPlaygroundBtn: typeof import('./src/components/layout-secure/app-bar/SPlaygroundBtn.vue')['default']
    SplitImage: typeof import('./src/components/base/split-view/SplitImage.vue')['default']
    SplitLeftCol: typeof import('./src/components/base/split-view/SplitLeftCol.vue')['default']
    SplitRightCol: typeof import('./src/components/base/split-view/SplitRightCol.vue')['default']
    SplitView: typeof import('./src/components/base/split-view/SplitView.vue')['default']
  }
}
