export {
  mdiGithub,
  mdiGoogle,
  mdiLink,
  mdiAccount,
  mdiSpaceInvaders,
  mdiDotsVertical,
  mdiFilterVariant,
  mdiMagnify,
  mdiMenu,
  mdiEmail,
  mdiTwitter,
  mdiWeb,
  mdiChevronLeft,
  mdiChevronRight,
  mdiRecord,
  mdiViewColumnOutline,
  mdiBookOpenPageVariantOutline,
  mdiStar,
  mdiMenuDownOutline,
  mdiTable,
  mdiWindowMaximize,
  mdiFormDropdown,
  mdiCircleOutline,
  mdiFormatLineWeight,
  mdiCardOutline,
  mdiCurrencyUsd,
} from '@mdi/js'
