export {
  mdiGithub,
  mdiGoogle,
  mdiLink,
  mdiAccount,
  mdiSpaceInvaders,
  mdiDotsVertical,
  mdiFilterVariant,
  mdiMagnify,
  mdiMenu,
  mdiEmail,
  mdiTwitter,
  mdiWeb,
  mdiChevronLeft,
  mdiChevronRight,
  mdiRecord,
  mdiViewColumnOutline,
  mdiBookOpenPageVariantOutline,
  mdiStar,
} from '@mdi/js'
